# Generated by Django 4.1.5 on 2023-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecfgusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delogin', models.CharField(max_length=20)),
                ('nmusuario', models.CharField(max_length=80)),
                ('desenha', models.CharField(blank=True, max_length=32, null=True)),
                ('flativo', models.CharField(blank=True, max_length=1, null=True)),
                ('desuperusuario', models.CharField(blank=True, max_length=32, null=True)),
                ('flrecebenovospoderes', models.CharField(blank=True, max_length=1, null=True)),
                ('nuusuario', models.IntegerField(blank=True, null=True)),
                ('cdescreventeass', models.IntegerField(blank=True, null=True)),
                ('cdescrevsubsttabeliaoass', models.IntegerField(blank=True, null=True)),
                ('flpodeatualizar', models.CharField(blank=True, max_length=1, null=True)),
                ('flenviaatocomerro', models.CharField(blank=True, max_length=1, null=True)),
                ('flredefinirformapagto', models.CharField(blank=True, max_length=1, null=True)),
                ('mmconfiguracoes', models.TextField(blank=True, null=True)),
                ('nmusuario_selotj', models.CharField(blank=True, max_length=250, null=True)),
                ('desenha_selotj', models.CharField(blank=True, max_length=250, null=True)),
                ('flvalidamsgselo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ecfgusuario',
                'managed': False,
            },
        ),
    ]
