# Generated by Django 4.1.5 on 2023-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtradigitalAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('delogin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nmusuario', models.CharField(max_length=80)),
                ('desenha', models.CharField(blank=True, max_length=32, null=True)),
                ('flativo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ECFGUSUARIO',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='ecfgusuario',
            table='ECFGUSUARIO',
        ),
    ]
