# Generated by Django 4.1.5 on 2023-02-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtradigitalAPI', '0002_usuarios_alter_ecfgusuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ecfgusuario',
            table='ecfgusuario',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='ecfgusuario',
        ),
    ]
