# Generated by Django 4.1.5 on 2023-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtradigitalAPI', '0003_alter_ecfgusuario_table_alter_usuarios_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecdtlogmein',
            fields=[
                ('cdlogmein', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('entryid', models.IntegerField(blank=True, null=True)),
                ('entry', models.CharField(blank=True, max_length=50, null=True)),
                ('technicianid', models.IntegerField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, max_length=30, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('waitingtime', models.DateTimeField(blank=True, null=True)),
                ('customfield0', models.CharField(blank=True, max_length=20, null=True)),
                ('customfield1', models.TextField(blank=True, null=True)),
                ('customfield2', models.CharField(blank=True, max_length=50, null=True)),
                ('customfield3', models.CharField(blank=True, max_length=30, null=True)),
                ('customfield4', models.CharField(blank=True, max_length=30, null=True)),
                ('customfield5', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('transferredto', models.CharField(blank=True, max_length=30, null=True)),
                ('transferredcomment', models.CharField(blank=True, max_length=100, null=True)),
                ('isleadtechnician', models.CharField(blank=True, max_length=10, null=True)),
                ('handingoff', models.CharField(blank=True, max_length=10, null=True)),
                ('nuprioridade', models.IntegerField(blank=True, null=True)),
                ('flbeep', models.CharField(blank=True, max_length=10, null=True)),
                ('teste', models.IntegerField(blank=True, null=True)),
                ('deresposta1', models.CharField(blank=True, max_length=2000, null=True)),
                ('deresposta2', models.CharField(blank=True, max_length=2000, null=True)),
                ('deresposta3', models.CharField(blank=True, max_length=2000, null=True)),
                ('depesquisaemitidapelotecnico', models.CharField(blank=True, max_length=10, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('lastdatestatus', models.DateTimeField(blank=True, null=True)),
                ('flprocessado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ecdtlogmein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vcdtfilalogmein',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('customfield0', models.CharField(blank=True, db_column='CustomField0', max_length=20, null=True)),
                ('customfield1', models.TextField(blank=True, db_column='CustomField1', null=True)),
                ('customfield2', models.CharField(blank=True, db_column='CustomField2', max_length=50, null=True)),
                ('customfield3', models.CharField(blank=True, db_column='CustomField3', max_length=30, null=True)),
                ('customfield4', models.CharField(blank=True, db_column='CustomField4', max_length=30, null=True)),
                ('customfield5', models.CharField(blank=True, db_column='CustomField5', max_length=100, null=True)),
                ('technician', models.CharField(blank=True, db_column='Technician', max_length=30, null=True)),
                ('cdcartorio', models.IntegerField(blank=True, db_column='CDCARTORIO', null=True)),
                ('nmpessoa', models.CharField(blank=True, db_column='NMPESSOA', max_length=150, null=True)),
                ('desituacaoimplantacao', models.CharField(blank=True, db_column='deSituacaoImplantacao', max_length=50, null=True)),
                ('imthumb', models.BinaryField(blank=True, db_column='IMTHUMB', max_length='max', null=True)),
                ('flbeep', models.CharField(blank=True, db_column='FLBEEP', max_length=10, null=True)),
            ],
            options={
                'db_table': 'VCDTFILALOGMEIN',
                'managed': False,
            },
        ),
    ]
